services:

  postgres:
    image: postgres:13
    container_name: witcher-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: witcher_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Ensures the service is only considered "healthy" when the database is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d witcher_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - witcher-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    # Healthcheck to ensure Zookeeper is ready before dependents start
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - witcher-net

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    # Healthcheck to ensure Kafka is ready to accept connections
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 5
      # Gives Kafka 40 seconds to start up before the health check is enforced
      start_period: 60s
    networks:
      - witcher-net

  eureka-server:
    build: ./service-discovery
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      # Prevents the server from trying to register with itself in a standalone setup
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
    networks:
      - witcher-net
    # Healthcheck to ensure Eureka is ready to register services
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 3s
      start_period: 30s # Give Eureka time to start before checking health
      retries: 5
        
  bestiary-and-armory-app:
    build: ./bestiary-and-armory-service
    container_name: bestiary-and-armory-app
    restart: unless-stopped
    ports:
      - "8100:8100"
    environment:
      SPRING_APPLICATION_NAME: bestiary-and-armory-app
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/witcher_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      # Ensures the service is fully functional before dependents start
      test: ["CMD", "curl", "-f", "-s", "http://localhost:8100/actuator/health"]
      interval: 15s
      timeout: 3s
      start_period: 30s # Give the service time to start before checking health
      retries: 5
    networks:
      - witcher-net

  witcher-contracts-app:
    build: ./witcher-contracts-service
    container_name: witcher-contracts-app
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      SPRING_APPLICATION_NAME: witcher-contracts-app
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092 # Connect to the internal Kafka listener
    depends_on:
      kafka:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      # Ensures the service is fully functional before dependents start
      test: ["CMD", "curl", "-f", "-s", "http://localhost:8200/actuator/health"]
      interval: 15s
      timeout: 3s
      start_period: 30s # Give the service time to start before checking health
      retries: 5
    networks:
      - witcher-net

  auth-service-app:
    build: ./auth-service
    container_name: auth-service-app
    restart: unless-stopped
    ports:
      - "8766:8766"
    environment:
      SPRING_APPLICATION_NAME: auth-service-app
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/witcher_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:8766/actuator/health"]
      interval: 15s
      timeout: 3s
      start_period: 30s # Give the service time to start before checking health
      retries: 5
    networks:
      - witcher-net

  api-gateway-app:
    build: ./api-gateway
    container_name: api-gateway-app
    restart: unless-stopped
    ports:
      - "8765:8765"
    environment:
      SPRING_APPLICATION_NAME: api-gateway-app
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "-s", "http://localhost:8765/actuator/health" ]
      interval: 15s
      timeout: 3s
      start_period: 30s # Give the gateway time to start before checking health
      retries: 5
    networks:
      - witcher-net


volumes:
  postgres-data:

# Define the shared network
networks:
  witcher-net:
    driver: bridge