server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: http://localhost:8766/api/v3/api-docs
      - name: Bestiary Service  
        url: http://localhost:8100/api/v3/api-docs
      - name: Contracts Service
        url: http://localhost:8200/api/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}